<template>
  <section class="section-padding">
    <div class="container thinnest-content">
      <div>
        <h1 class="mb-3">{{articleInfo.title}}</h1>
	      <img v-if="articleInfo.image !== 'title.jpg'" :src="`/img/articles/${articleInfo.image}`" :alt="articleInfo.title" class="mb-3">

	      <p>As a young man, Nelson Mandela worked as a law clerk in Johannesburg, South Africa. Among his coworkers were lawyers and clerks with formal degrees—some of them from Fort Hare, the same university he had been expelled from for protesting against discrimination. Out of all of his well-educated coworkers, there was one standout. Gaur Radebe was sharp, confident, and had a deep understanding of both the laws that governed the land and how they were used to mistreat native South Africans. He was more capable than most of their other colleagues, and very well spoken. But what struck Nelson Mandela most was that Radebe, like himself, had no university degree.</p>

	      <p>This was a turning point in Mandela’s life. Education, it turned out, was about more than attending lectures and taking exams. It was curiosity, practice, experience, and application in the real world. Education was about competence, not credential. Radebe was living proof that you didn’t need a university degree to be an educated person.</p>

	      <p>Employers often use a college degree to sort through job applicants. No bachelor’s degree? Hit the road, jack. This happens because it is difficult to gauge how well someone will perform a certain job without seeing them work. A university degree provides a common measuring stick with which to compare candidates. The problem with sorting people based on education level is that a college-educated person isn’t necessarily more competent than someone without a degree. Some people spend four years at a university cramming for exams and playing Fortnite. They emerge with almost nothing to show for their time and tuition (except maybe a degree).</p>

	      <p>In school, I took a research course that allowed me to pick a topic from the tech world and study it on my own for a semester. The professor in charge had one requirement to pass the course—I needed artifacts. By artifacts, he meant some physical evidence that I had done some kind of work during the semester. Without evidence, how could he know if I had actually spent three months doing research?</p>

	      <p>A college degree is an artifact. It shows that you got into a university, learned enough to not fail all of your classes, and persevered to the end to some extent. It is an indicator of your potential competence. A degree is not the only artifact employers find interesting. SATs, GPAs, LSATs, and GMATs are all artifacts. A portfolio (be it filled with articles or artwork) is an artifact. A criminal record is an artifact. Instagram accounts, IT certifications, and credit scores. These are all artifacts generated by your actions, and some are more impactful than others.</p>

	      <p>There is a balance to be struck here. Artifacts support your claims to competence, but they do not equate to competence. If you let your credentials and artifacts oversell your abilities, you will be a disappointment to the people that hire you. On the flip side, if you are competent in your field but can’t prove it to anyone, opportunities will be few and far between.</p>

	      <p>Artifacts should arise naturally as you strive to improve your level of competence. If you strive to understand what you are studying in school, your GPA will be an accurate measure of your understanding. If you focus more on grades and degrees than on learning, your artifacts will get you into situations where you will underwhelm and fall behind (or force you to rise to the occasion, who knows).</p>

	      <p>Artifacts and credentials will attach themselves to you as you put effort into learning, experimentation, and improving your abilities. Focus on competence, and credentials will come.</p>

      </div>
	    <ArticleShareLinks :slug="articleInfo.slug" />
    </div>
  </section>
</template>

<script setup>
import articlesList from "@/assets/articlesList";

const router = useRouter()
const { currentRoute } = router
const articleInfo = articlesList.find(article => article.slug === currentRoute.value.fullPath.replace('/articles/',''))
// meta tags
useArticleSeo(articleInfo)
</script>